#!/usr/bin/env python3

import yaml
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("infile", help="The yaml file you want to convert")
args = parser.parse_args()
with open(args.infile, 'r') as stream:
    try:
        print("# File generated by yaml2ssh")
        data = yaml.safe_load(stream)
        for group in data:
            config = data[group]
            keys = [key for key in config if key != 'Hosts']
            hosts = config['Hosts']
            for host in hosts:
                if isinstance(host, str):
                    print('Host {}'.format(host))

                    for key in keys:
                        print('     {} {}'.format(key, config[key]))
                else:
                    a = host
                    for host in a:
                        hostkeys = keys + list(set(a[host]) - set(keys))
                        print('Host {}'.format(host))
                        if 'Hostname' not in hostkeys:
                            print('     Hostname {}'.format(host))
                        for key in hostkeys:
                            if key in a[host]:
                                if a[host][key]:
                                    print('     {} {}'.format(key, a[host][key]))
                            else:
                                print('     {} {}'.format(key, config[key]))
    except yaml.YAMLError as exc:
        print(exc)
